'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
type Attempt={id:string;jobId:string|null;executor:string;model:string|null;status:string;createdAt:string;finishedAt:string|null;errorCode:string|null};
export default function AuditClient(){
 const [rows,setRows]=useState<Attempt[]>([]),[selected,setSelected]=useState<Attempt|null>(null),[direction,setDirection]=useState<'input'|'output'>('input'),[payload,setPayload]=useState(''),[error,setError]=useState(''),[jobId,setJobId]=useState(''),[status,setStatus]=useState('');
 async function load(before?:string,beforeId?:string){setError('');try{const query=new URLSearchParams();if(jobId)query.set('jobId',jobId);if(status)query.set('status',status);if(before)query.set('before',before);if(beforeId)query.set('beforeId',beforeId);const r=await fetch(`/api/admin/task-audits?${query}`,{cache:'no-store'});if(!r.ok)throw Error();setRows((await r.json()).attempts);}catch{setRows([]);setSelected(null);setPayload('');setError('無法讀取紀錄，請確認管理員權限。');}}
 useEffect(()=>{let active=true;void fetch('/api/admin/task-audits',{cache:'no-store'}).then(async r=>{if(!r.ok)throw Error();const data=await r.json();if(active)setRows(data.attempts);}).catch(()=>{if(active)setError('無法讀取紀錄，請確認管理員權限。');});return()=>{active=false;};},[]);
 useEffect(()=>{let active=true;setPayload('');if(!selected)return;void(async()=>{try{const r=await fetch(`/api/admin/task-audits/${selected.id}/payload?direction=${direction}`,{cache:'no-store'});if(!r.ok)throw Error();const data=await r.json();if(active)setPayload(data.available?`${data.partial?'［未完成紀錄］\n':''}${data.text}`:'未有內容或內容已不可用。');}catch{if(active){setPayload('');setError('內容不可用或權限已撤銷。');}}})();return()=>{active=false;};},[selected,direction]);
 return <main style={{padding:24,maxWidth:1100,margin:'auto'}}><Link href='/admin/users'>帳號管理</Link><h1>任務輸入／輸出紀錄</h1><p>目前只供合成資料驗證。紀錄查閱會被審計；不代表已接駁學校 Portal。</p><form onSubmit={e=>{e.preventDefault();void load();}}><label>任務 ID <input value={jobId} onChange={e=>setJobId(e.target.value)}/></label><label>狀態 <select value={status} onChange={e=>setStatus(e.target.value)}><option value=''>全部</option>{['RUNNING','SUCCEEDED','FAILED','CANCELLED','INTERRUPTED','DENIED'].map(s=><option key={s}>{s}</option>)}</select></label><button>篩選</button></form>{error&&<p role='alert'>{error}</p>}<table><thead><tr><th>時間</th><th>執行器／模型</th><th>狀態</th><th>紀錄</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{new Date(r.createdAt).toLocaleString()}</td><td>{r.executor} {r.model}</td><td>{r.status}</td><td><button onClick={()=>{setError('');setSelected(r);}}>查看 {r.id.slice(0,8)}</button></td></tr>)}</tbody></table>{rows.length===50&&<button onClick={()=>void load(rows[rows.length-1].createdAt,rows[rows.length-1].id)}>較早紀錄</button>}{selected&&<section><h2>{selected.executor} · {selected.status}</h2><p>{selected.id} · {selected.errorCode}</p>{selected.jobId&&<p>任務：{selected.jobId}</p>}<button onClick={()=>setDirection('input')} aria-pressed={direction==='input'}>輸入</button><button onClick={()=>setDirection('output')} aria-pressed={direction==='output'}>輸出</button><pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{payload}</pre></section>}</main>;
}
